/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ViewEventsImport } from './routes/view-events'
import { Route as AddEventImport } from './routes/add-event'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ViewEventsRoute = ViewEventsImport.update({
  id: '/view-events',
  path: '/view-events',
  getParentRoute: () => rootRoute,
} as any)

const AddEventRoute = AddEventImport.update({
  id: '/add-event',
  path: '/add-event',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/add-event': {
      id: '/add-event'
      path: '/add-event'
      fullPath: '/add-event'
      preLoaderRoute: typeof AddEventImport
      parentRoute: typeof rootRoute
    }
    '/view-events': {
      id: '/view-events'
      path: '/view-events'
      fullPath: '/view-events'
      preLoaderRoute: typeof ViewEventsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-event': typeof AddEventRoute
  '/view-events': typeof ViewEventsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-event': typeof AddEventRoute
  '/view-events': typeof ViewEventsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/add-event': typeof AddEventRoute
  '/view-events': typeof ViewEventsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add-event' | '/view-events'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add-event' | '/view-events'
  id: '__root__' | '/' | '/add-event' | '/view-events'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddEventRoute: typeof AddEventRoute
  ViewEventsRoute: typeof ViewEventsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddEventRoute: AddEventRoute,
  ViewEventsRoute: ViewEventsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/add-event",
        "/view-events"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/add-event": {
      "filePath": "add-event.tsx"
    },
    "/view-events": {
      "filePath": "view-events.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
